project:
  type: website
  output-dir: docs
  title: "TidyTuesdays"

website:
  navbar:
    pinned: true
    collapse: true
    left:
      - icon: house-fill
        text: "Home"
        href: TidyTuesdays.qmd
      - icon: github
        text: "Github"
        href: https://github.com/Hippolyte-Menou/TidyTuesdays

  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: TidyTuesdays.qmd
      - section: "TidyTuesdays Data Stories"
        contents:
          - text: "2018-04-03 - US Tuition Costs"
            href: 2018-04-03 - US Tuition Costs/2018-04-03 - US Tuition Costs.qmd
          - text: "2019-02-26 - French Train Delays"
            href: 2019-02-26 - French Train Delays/2019-02-26 - French Train Delays.qmd
          - text: "2023-02-21 - Bob Ross Paintings"
            href: 2023-02-21 - Bob Ross Paintings/2023-02-21 - Bob Ross Paintings.qmd
          - text: "2023-03-14 - European Drug Development"
            href: 2023-03-14 - European Drug Development/2023-03-14 - European Drug Development.qmd
      - section: "TidyTuesdays Data Visualization"
        contents:
          - text: "Hi!"
      - section: "Helpers"
        contents:
          - text: "Advanced facetting techniques"
            href: tips/Advanced facetting techniques.qmd
          - text: "Custom theme functions"  
            href: tips/Custom theme functions.qmd
          - text: "Advanced geometries with ggforce"  
            href: tips/Advanced geometries with ggforce.qmd
          - text: "Data Emphasis"  
            href: tips/Data Emphasis.qmd
          - text: "Advanced Nested Faceting with ggh4x"  
            href: tips/Advanced Nested Faceting with ggh4x.qmd
          - text: "Multiple Color Scales with ggnewscale"  
            href: tips/Multiple Color Scales with ggnewscale.qm
          - text: "Common gotchas with text"  
            href: tips/Common gotchas with text.qmd
          - text: "Ordered Barcharts"  
            href: tips/Ordered Barcharts.qmd
          - text: "Complex Layouts with patchwork"  
            href: tips/Complex Layouts with patchwork.qmd
          - text: "Saving and reusing themes"  
            href: tips/Saving and reusing themes.qmd
          - text: "Custom Color Palettes"  
            href: tips/Custom Color Palettes.qmd
          - text: "Theme elements"  
            href: tips/Theme elements.qmd

editor: visual

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

execute:
  error: true
  warning: false
  message: false
  freeze: auto
