project:
  type: website
  output-dir: docs
  title: "TidyTuesdays"

website:
  navbar:
    pinned: true
    collapse: true
    left:
      - icon: house-fill
        text: "Home"
        href: TidyTuesdays.qmd
      - icon: github
        text: "Github"
        href: https://github.com/Hippolyte-Menou/TidyTuesdays


  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: TidyTuesdays.qmd
      - section: "TidyTuesdays Data Stories"
        contents:
          - text: "2018-04-03 - US Tuition Costs"
            href: 2018-04-03 - US Tuition Costs/2018-04-03 - US Tuition Costs.qmd
          - text: "2019-01-15 - Space Launches"
            href: 2019-01-15 - Space Launches/2019-01-15 - Space Launches.qmd
          - text: "2019-02-26 - French Train Delays"
            href: 2019-02-26 - French Train Delays/2019-02-26 - French Train Delays.qmd
          - text: "2023-02-21 - Bob Ross Paintings"
            href: 2023-02-21 - Bob Ross Paintings/2023-02-21 - Bob Ross Paintings.qmd
          - text: "2023-03-14 - European Drug Development"
            href: 2023-03-14 - European Drug Development/2023-03-14 - European Drug Development.qmd
      - section: "TidyTuesdays Data Visualization"
        contents:
          - text: "Hi!"
      - section: "Helpers"
        contents:
          - tips/*.qmd


editor: visual

format:
  html:
    theme:
      light: [yeti, theme-light.scss]
      dark: [superhero, theme-dark.scss]
    code-theme: "monokai"
    css: styles.css
    toc: true
    toc-title: "Contents"
    toc-depth: 3
    toc-back-to-top: true
    code-fold: true
    code-summary: "Show the code"
    code-copy: true
    code-copy-label: "Copy Code"
    code-copy-message: "Code copied to clipboard"
    code-copy-error: "Error copying code"
    code-copy-success: "Code copied successfully"
    code-copy-timeout: 5000

    

execute:
  error: true
  warning: false
  message: false
  # freeze: auto
  # cache: true

